<?php
/**
 * runtime tests
 *
 * PHP Version 5
 *
 * @category  Test
 * @package   Mp3Indexer
 * @author    Lucas S. Bickel <hairmare@purplehaze.ch>
 * @copyright 2012 - Alle Rechte vorbehalten
 * @license   GPL http://www.gnu.org/licenses/gpl-3.0.txt
 * @link      http://github.com/purplehazech/mp3-indexer
 */

require_once __DIR__.'/../../..//src/Mp3Indexer/Log/Stdout.php';

/**
 * Test class for Mp3Indexer_Log_Stdout.
 * Generated by PHPUnit on 2012-05-20 at 22:43:11.
 *
 * @category Test
 * @package  Mp3Indexer
 * @author   Lucas S. Bickel <hairmare@purplehaze.ch>
 * @license  GPL http://www.gnu.org/licenses/gpl-3.0.txt
 * @link     http://github.com/purplehazech/mp3-indexer
 */
class Mp3Indexer_Log_StdoutTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Mp3Indexer_Log_Stdout
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->dispatcherMock = $this->getMock('sfEventDispatcher');
        $this->object = new Mp3Indexer_Log_Stdout(
            $this->dispatcherMock
        );
    }

    /**
     * check for output
     *
     * @covers Mp3Indexer_Log_Stdout::logEvent
     *
     * @return void
     */
    public function testLogEvent()
    {
        $this->expectOutputString("Message: test\n");

        $event = new stdClass;
        $event->message = 'test';
        $event->type = 'error';

        $this->object->logEvent($event);
    }
}
