<?php
/**
 * runtime tests
 *
 * PHP Version 5
 *
 * @category  Test
 * @package   Mp3Indexer
 * @author    Lucas S. Bickel <hairmare@purplehaze.ch>
 * @copyright 2012 - Alle Rechte vorbehalten
 * @license   GPL http://www.gnu.org/licenses/gpl-3.0.txt
 * @link      http://github.com/purplehazech/mp3-indexer
 */

require_once __DIR__.'/../../src/Mp3Indexer/AudioFileRecursiveFilterIterator.php';

/**
 * Test class for Mp3Indexer_AudioFileRecursiveFilterIterator.
 * Generated by PHPUnit on 2012-05-20 at 19:53:54.
 *
 * @category Test
 * @package  Mp3Indexer
 * @author   Lucas S. Bickel <hairmare@purplehaze.ch>
 * @license  GPL http://www.gnu.org/licenses/gpl-3.0.txt
 * @link     http://github.com/purplehazech/mp3-indexer
 */
class Mp3Indexer_AudioFileRecursiveFilterIteratorTest extends PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        vfsStreamWrapper::register();
        vfsStreamWrapper::setRoot(new vfsStreamDirectory(__DIR__.'/../fixtures/testDir'));
    }

    /**
     * @todo Implement testAccept().
     *
     * @covers Mp3Indexer_AudioFileRecursiveFilterIterator::accept
     *
     * @return void
     */
    public function testAccept()
    {
        $iterator = Mp3Indexer_AudioFileRecursiveFilterIterator(
            new RecursiveDirectoryIterator(
                vfsStreamWrapper::getRoot()
            )
        );
        $this->assertTrue($iterator->hasChildren());

        $files = array();
        foreach ($iterator->getChildren() AS $kid) {
            foreach ($kid AS $file) {
                $files[] = $file;
            }
        }

        $this->assertContains('test1.mp3', $file);
        $this->assertContains('test2.mp3', $file);
    }
}
