<?php
/**
 * runtime tests
 *
 * PHP Version 5
 *
 * @category  Test
 * @package   Mp3Indexer
 * @author    Lucas S. Bickel <hairmare@purplehaze.ch>
 * @copyright 2012-2013 - Alle Rechte vorbehalten
 * @license   GPL http://www.gnu.org/licenses/gpl-3.0.txt
 * @link      http://github.com/purplehazech/mp3-indexer
 */

require_once __DIR__.'/../../src/Mp3Indexer/AudioFileRecursiveFilterIterator.php';

/**
 * Test class for Mp3Indexer_AudioFileRecursiveFilterIterator.
 * Generated by PHPUnit on 2012-05-20 at 19:53:54.
 *
 * @category Test
 * @package  Mp3Indexer
 * @author   Lucas S. Bickel <hairmare@purplehaze.ch>
 * @license  GPL http://www.gnu.org/licenses/gpl-3.0.txt
 * @link     http://github.com/purplehazech/mp3-indexer
 */
class Mp3Indexer_AudioFileRecursiveFilterIteratorTest
    extends PHPUnit_Framework_TestCase
{
    /**
     * @var Mp3Indexer_AudioFileRecursiveFilterIterator
     */
    var $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        // what i setup here looks nice but mostly doesn't work
        // moving on...
        $mp3Mock = $this->getMock('stdClass');
        $mp3Mock->expects($this->any())
            ->method('getExtension')
            ->will($this->returnValue('mp3'));

        $this->recursorMock = new RecursiveArrayIterator(
            array(
                    $mp3Mock, $mp3Mock
            )
        );
        $this->recursorMock->next();

        $this->object = new Mp3Indexer_AudioFileRecursiveFilterIterator(
            $this->recursorMock
        );
    }

    /**
     * check if accept method behaves
     *
     * @covers Mp3Indexer_AudioFileRecursiveFilterIterator::accept
     *
     * @return void
     */
    public function testAccept()
    {
        $this->assertTrue($this->object->accept('test'));
    }
}
